name: Trigger auto deployment for kkfev-dev-aca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/kkfev-dev-aca-AutoDeployTrigger-bf25387e-07b1-4eca-92a7-c92457ffed65.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: kkfevcontainerreg.azurecr.io
          username: ${{ secrets.KKFEVDEVACA_REGISTRY_USERNAME }}
          password: ${{ secrets.KKFEVDEVACA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kkfevcontainerreg.azurecr.io/kkfev-dev-aca:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KKFEVDEVACA_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n kkfev-dev-aca -g kkfev-east-us-rg --server kkfevcontainerreg.azurecr.io --username  ${{ secrets.KKFEVDEVACA_REGISTRY_USERNAME }} --password ${{ secrets.KKFEVDEVACA_REGISTRY_PASSWORD }}
            az containerapp update -n kkfev-dev-aca -g kkfev-east-us-rg --image kkfevcontainerreg.azurecr.io/kkfev-dev-aca:${{ github.sha }}
